{"uuid": "84adf6f1-41ec-45df-9b28-a49e81775850", "children": ["f95ae2a3-03d4-4413-af65-5925228362a0", "9482ca1c-ef26-4a46-b8fc-756426912e55", "340dc222-ad6f-4e89-aa9c-0a47d7f3ec64"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "TypeError: to_capabilities() missing 1 required positional argument: 'self'\n", "trace": "  File \"C:\\Users\\ChenHuaishu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ChenHuaishu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ChenHuaishu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\learning\\python\\pycharm\\project\\webui_frame\\conftest.py\", line 54, in init_driver\n    GlobalDriver.driver = InitDriver(browser_name, remote_url='http://127.0.0.1:4444/wb/hub')   # 生产driver对象\n  File \"E:\\learning\\python\\pycharm\\project\\webui_frame\\common\\driver.py\", line 51, in __init__\n    self.driver = webdriver.Remote(remote_url, options.to_capabilities(), keep_alive=True)\n"}, "start": 1678095003465, "stop": 1678095003466}], "start": 1678095003465, "stop": 1678095003599}